force-app/main/default/objects/ChildFieldDetails__mdt/ChildFieldDetails__mdt.object-meta.xml
<CustomObject>
    <label>Child Field Details</label>
    <pluralLabel>Child Field Details</pluralLabel>
</CustomObject>

force-app/main/default/objects/ChildFieldDetails__mdt/fields/FieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>FieldAPIName__c</fullName>
    <label>Field API Name</label>
    <metadataRelationshipControllingField>ChildFieldDetails__mdt.ObjectAPIName__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Child_Field_Details</relationshipLabel>
    <relationshipName>Child_Field_Details</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/ChildFieldDetails__mdt/fields/ObjectAPIName__c.field-meta.xml
<CustomField>
    <fullName>ObjectAPIName__c</fullName>
    <label>Object API Name</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Child_Field_Details</relationshipLabel>
    <relationshipName>Child_Field_Details</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/ChildFieldDetails__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ChildFieldDetails__mdt/fields/ParentObjectDetails__c.field-meta.xml
<CustomField>
    <fullName>ParentObjectDetails__c</fullName>
    <label>Parent Object Details</label>
    <referenceTo>ParentObjectDetails__mdt</referenceTo>
    <relationshipLabel>Child Field Details</relationshipLabel>
    <relationshipName>Child_Field_Details</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/ChildFieldDetails__mdt/fields/UseFor__c.field-meta.xml
<CustomField>
    <fullName>UseFor__c</fullName>
    <label>Use For (Purpose)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Edit Record</fullName>
                <default>true</default>
                <label>Edit Record</label>
            </value>
            <value>
                <fullName>Add New Record</fullName>
            </value>
            <value>
                <fullName>Both Edit/New Record</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ParentObjectDetails__mdt/ParentObjectDetails__mdt.object-meta.xml
<CustomObject>
    <label>Parent Object Details</label>
    <pluralLabel>Parent Object Details</pluralLabel>
</CustomObject>

force-app/main/default/objects/ParentObjectDetails__mdt/fields/ObjectAPIName__c.field-meta.xml
<CustomField>
    <fullName>ObjectAPIName__c</fullName>
    <label>Object API Name</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Parent_Object_Details</relationshipLabel>
    <relationshipName>Parent_Object_Details</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/ParentObjectDetails__mdt/fields/PlaceUsed__c.field-meta.xml
<CustomField>
    <fullName>PlaceUsed__c</fullName>
    <label>Place to be Used</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MetadataRetreiver.cls
public with sharing class MetadataRetreiver {
    /*
        SELECT Id, FieldAPIName__c, FieldAPIName__r.QualifiedApiName, ParentObjectDetails__c, ObjectAPIName__c,
            ObjectAPIName__r.QualifiedApiName, Order__c 
        FROM 
            ChildFieldDetails__mdt 
        WHERE 
            ParentObjectDetails__r.ObjectAPIName__r.QualifiedApiName = 'Contact' AND 
            ParentObjectDetails__r.PlaceUsed__c = 'Home Page' 
        Order BY 
            Order__c ASC
    */
    @AuraEnabled(cacheable=true)
    public static List<sObject> getMetadataObjectRecords(String objectApiName, String placeToBeUsed, String usedFor){
        return [
            SELECT
                Id,
                FieldAPIName__c,
                FieldAPIName__r.QualifiedApiName,
                ObjectAPIName__c,
                ObjectAPIName__r.QualifiedApiName,
                ParentObjectDetails__c,
                Order__c,
                UseFor__c
            FROM
                ChildFieldDetails__mdt
            WHERE
                ParentObjectDetails__r.ObjectAPIName__r.QualifiedApiName =: objectApiName AND
                ParentObjectDetails__r.PlaceUsed__c =: placeToBeUsed AND
                ( UseFor__c =: usedFor OR UseFor__c = 'Both Edit/New Record' )
            ORDER BY
                Order__c ASC
            LIMIT
                100
        ];
    }
}